# Generated by Django 5.1.1 on 2024-10-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_shippingaddress_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
