# Generated by Django 5.1.1 on 2024-10-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_userprofile_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='google_id',
        ),
    ]
